workflows:
  android-build:
    name: Build APK
    environment:
      vars:
        ANDROID_HOME: /opt/android/sdk
    scripts:
      - name: Install Node.js dependencies
        script: |
          npm install
      - name: Build web project
        script: |
          npm run build
      - name: Copy build to Android
        script: |
          npx cap copy
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
